### ISSUE TITLE
Error when updating items

### ISSUE THREAD

**Issue by sudsys4u** [syswhiz/Syswhiz#7] opened 2017-04-14 00:38 UTC
When I update an item I get the following error.  When I go back to site, it seems to still do the update, even though getting this error.

Fatal error: Cannot use object of type WP_Error as array in /home/content/a2pewpnas01_data03/69/3970369/html/wp-content/plugins/woocommerce/includes/class-wc-product-attribute.php on line 80

**Comment by Brown-Ninja** [comment] 2017-04-14 01:51
Is this error reproducible with a specific product? I would like to see this error myself on my  PC. If there is a way to reproduce it, please let me know. I will get it resolved.

**Comment by sudsys4u** [comment] 2017-04-14 02:01
I think I narrowed it down to the images.  When you add an image to a
product then select Update you get the error. I originally thought it was
still doing the updates, but it is not saving the photos I added.

**Comment by sudsys4u** [comment] 2017-04-14 02:12
I just recreated it while updating the Product Short Description section
for the Lip Balm with SPF.

**Comment by Brown-Ninja** [comment] 2017-04-21 22:11
Fix has been released and added to sudsys4u - https://github.com/woocommerce/woocommerce/issues/14429

**Comment by Brown-Ninja** [comment] 2017-04-21 22:12
@sudsys4u  I was unable to reproduce this issue anymore. Please give it a shot. If you are still able to reproduce this issue, I will reopen the ticket.

**Closed** 2017-04-21 22:12 UTC
Labels: bug
